global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1m
  external_labels:
    monitor: prometheus

scrape_configs:
  - job_name: prometheus-grafana
    honor_timestamps: true
    scrape_interval: 1s
    scrape_timeout: 1s
    metrics_path: /metrics
    scheme: http
    metric_relabel_configs:
      - source_labels: [__address__]
        separator: ;
        regex: (.*)
        target_label: instance
        replacement: Grafana-EC2-MASTER
        action: replace
    static_configs:
      - targets:
          - 3.108.63.229:9100            # node exportor or apache exportor

  - job_name: node-1
    honor_timestamps: true
    scrape_interval: 1s
    scrape_timeout: 1s
    metrics_path: /metrics
    scheme: http
    metric_relabel_configs:
      - source_labels: [__address__]
        separator: ;
        regex: (.*)
        target_label: instance
        replacement: node-1
        action: replace
    static_configs:
      - targets:
          - 13.201.21.140:9100               # node exportor or apache exportor

